Webapp-master/mysite/blog/urls.py
from django.urls import path, include
from . import views
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'blog'

urlpatterns = [
    path('',views.post_list,name='post_list'),
    #path('',views.PostListView.as_view(),name='PostListView'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.profile, name='profile'),
    path('', views.home, name="home"),
]

Webapp-master/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Webapp-master/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class Post(models.Model):
    STATUS_CHOISES=(('draft','Draft'),('published','Published'),)

    title=models.CharField(max_length=250,verbose_name='Post name')
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,on_delete=models.CASCADE, related_name='blog_posts',verbose_name='Author')
    short_description=models.CharField(max_length=400,verbose_name='Description')
    tags = TaggableManager(blank=True)
    publish=models.DateTimeField(verbose_name='Publish date', default=timezone.now)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Create date')
    updated = models.DateTimeField(auto_now=True, verbose_name='Update')
    status=models.CharField(max_length=10, choices=STATUS_CHOISES,default='draft')
    image=models.ImageField(upload_to='porodact_images/',verbose_name='Image',blank=False)

    class Meta:
        ordering=('-publish',)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])

def save_images(instance,filename):
    post_id=instance.post.id
    return 'gallery_images/{}/{}'.format(post_id,filename)

class PostPoint(models.Model):
    post_header = models.CharField(max_length=250, default='Header')
    post=models.ForeignKey(Post,on_delete=models.CASCADE,default=None)
    post_point_text=models.TextField(verbose_name='Post point')
    post_images = models.ImageField(upload_to=save_images, verbose_name='Image point', blank=True,)
    def __str__(self):
        return 'Post point {}'.format(self.post.title)

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return 'Коментарь {} про {}'.format(self.name, self.post)

class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class TagModel(models.Model):
    title = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return self.title

class Trip(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    tags = models.CharField(max_length=255, blank=True)
    def __str__(self):
        return self.name

Webapp-master/mysite/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Comment
from .models import Trip
from django.core.validators import ValidationError

class CommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name","email","body")


class SearchForm(forms.ModelForm):
    tags = forms.CharField(label="Tags", max_length=255, help_text="Enter one or more tags, separated by commas")

    class Meta:
        model = Trip
        fields = ("name", "tags", "description")

class RegistrationForm(UserCreationForm):
    email = forms.CharField(max_length=30,label="email", required=True, help_text="Обов'язкове поле", widget=forms.TextInput(attrs={
        'placeholder': 'Enter your email address',
        "id": "inputEmail",
        "class": "form",
    }))
    first_name = forms.CharField(max_length=30, required=True, help_text="Обов'язкове поле", widget=forms.TextInput(attrs={
        "class":"form-control",
        "placeholder":"login",
        "id":"inputFirstName",

    }))
    last_name = forms.CharField(max_length=30, required=True, help_text="Обов'язкове поле", widget=forms.TextInput(attrs={
        "id":"inputLastName",
        "class":"form-control",
        "placeholder":"login",
    }))

    class Meta:
        model = User
        fields = [
            'username','email', 'first_name',
            'last_name', 'password1', 'password2'
        ]

        def __init__(self, *args, **kwargs):
            super(RegistrationForm).__init__(*args, **kwargs)
            self.fields['username'].help_texts = "Обов'язкове поле тільки букви, цифри та символи @/./+/-/_."
            self.fields['password1'].help_texts = "Обов'язково використовувати букви та цифри"
            self.fields['password2'].help_texts = "Повторіть ще раз свій пароль"

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={
        "id":"inputLogin",
        "class":"form-control",
        "placeholder":"login",
    }))
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        "type": "password",
        "id":"inputPassword",
        "class":"form-control",
        "placeholder":"0000",
    }))

Webapp-master/mysite/blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from django.contrib.auth.views import LoginView
from django.views import View
from .models import Post, PostPoint, Comment, User
from .forms import CommentForms, LoginForm, RegisterForm
from django.db.models import Count
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

from taggit.models import Tag

@login_required(login_url='blog:login')
def post_list(request, tag_slug=None):
    object_list=Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    items_per_page = 3
    paginator=Paginator(object_list, items_per_page)
    page = request.GET.get('page', 1)
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'posts':posts})




def post_detail(request, year, month, day, post):
    post_object = get_object_or_404(Post, slug=post, status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    post_points = PostPoint.objects.filter(post=post_object)

    comments = post_object.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':

        comment_form = CommentForms(data=request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            new_comment = Comment(post=post_object, name=cd['name'], email=cd['email'], body=cd['body'])
            new_comment.save()
    else:
        comment_form = CommentForms()

    post_tags_ids=post_object.tags.values_list('id',flat=True)
    similar_posts=Post.objects.filter(tags__in=post_tags_ids,status='published').exclude(id=post_object.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:3]

    return render(request, 'blog/post/detail.html', {'post': post_object,
                                                     'post_points': post_points,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts
                                                     })

@login_required(login_url='blog:login')
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or password is incorrect!')
    context = {}
    return render(request, 'registration/login.html', context)

def logout_view(request):
    messages.success(request, 'Successfully logged out')
    logout(request)
    return redirect('login')

def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect('login')

    context = {'form':form}
    return render(request, 'registration/register.html', context)

def home(request):
    if 'user' in request.session:
        current_user = request.session['user']
        param = {'current_user':current_user}
        return render(request, 'blog/base.html', param)
    else:
        return redirect('login')
    return render(request, 'registration/login.html')


@login_required
def profile(request):
    return render(request, 'blog/account/dashboard.html')

Webapp-master/mysite/blog/templates/blog/base.html
{%load static%}
<!DOCTYPE html>
<html lang="en">

<head>
   <meta charset="UTF-8">
   <title>{%block title%} {% endblock %}</title>
   <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/css/bootstrap.min.css" integrity="sha384-TX8t27EcRE3e/ihU7zmQxVncDAy5uIKz4rEkgIXeMed4M0jlfIDPvg6uqKI2xXr2" crossorigin="anonymous">
   <link rel="stylesheet" href="{% static 'css/style.css' %}">
   
</head>
<body>
   {% block navbar %}
     <nav class="navbar navbar-expand-lg navbar-dark bg-primary">
         <a class="navbar-brand" href="{% url 'blog:post_list' %}">Navbar</a>
         <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
             <span class="navbar-toggler-icon"></span>
         </button>

         <div class="collapse navbar-collapse justify-content-center" id="nav-filter">
             <form class="form-inline my-2 my-lg-0"> {% csrf_token %}
                <input class="form-control mr-sm-2" type="search" placeholder="Search" aria-label="Search" name="search_view">
                <button class="btn btn-outline-success my-2 my-sm-0" type="submit">Search</button>
            </form>
         </div>

         <div id="header"class="navbar navbar-expand-lg navbar-dark bg-primary collapse navbar-collapse justify-content-end">
            <span class=user>
                {% if request.user.is_authenticated %}
                <div class="profile-icon">
                    <a href="{% url 'blog:profile' %}" class="pr-3">
                        {{ requset.user.first_name }}
                        <span class="profile-text">Profile</span>
                    </a>
                </div>
                    Ви {{ user.username }}
                {% else %}
                    <a href="{% url "blog:login" %}">
                        Login
                    </a>
                {% endif %}
            </span>
            <button class="navbar-toggler" type="button" data-toggle="collapse" data-target="#navbarSupportedContent" aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation"></button>
        </div>    
        </nav>
   {% endblock %}

        <section class="feautered-products">
                <div id="content">
                    {% block content %}
                    {% endblock %}
                </div>
        </section>

<script src="https://code.jquery.com/jquery-3.6.4.slim.min.js" integrity="sha384-DfXdz2htPH0lsSSs5nCTpuj/zy4C+OGpamoFVy38MVBnE+IbbVYUew+OrCXaRkfj" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js" integrity="sha384-ho+j7jyWK8fNQe+A12Hb8AhRq26LrZ/JpcUGGOn+Y7RsweNrtN/tE3MoK7ZeZDyx" crossorigin="anonymous"></script>
<script src="{% static 'index.js' %}"></script>

</body>

</html>