Webapp-master/mysite/blog/urls.py
from django.urls import path, include
from . import views
from .views import *
from django.contrib.auth import views as auth_views

app_name = 'blog'

urlpatterns = [
    path('',views.post_list,name='post_list'),
    #path('',views.PostListView.as_view(),name='PostListView'),
    path('<int:year>/<int:month>/<int:day>/<slug:post>/',views.post_detail,name='post_detail'),
    path('tag/<slug:tag_slug>/',views.post_list, name='post_list_by_tag'),
    path('register/', views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(), name='login'),
    path('logout/', views.logout_view, name='logout'),
    path('dashboard/', views.profile, name='profile'),
    path('', views.home, name="home"),
]

Webapp-master/mysite/mysite/urls.py
from django.contrib import admin
from django.urls import path,include
from django.conf.urls.static import static
from django.conf import settings


urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls',namespace='blog')),
    path('accounts/', include('django.contrib.auth.urls')),
]+static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Webapp-master/mysite/blog/models.py
from django.db import models
from django.utils import timezone
from django.contrib.auth.models import User
from django.urls import reverse
from taggit.managers import TaggableManager

class Post(models.Model):
    STATUS_CHOISES=(('draft','Draft'),('published','Published'),)

    title=models.CharField(max_length=250,verbose_name='Post name')
    slug=models.SlugField(max_length=250,unique_for_date='publish')
    author=models.ForeignKey(User,on_delete=models.CASCADE, related_name='blog_posts',verbose_name='Author')
    short_description=models.CharField(max_length=400,verbose_name='Description')
    tags = TaggableManager(blank=True)
    publish=models.DateTimeField(verbose_name='Publish date', default=timezone.now)
    created = models.DateTimeField(auto_now_add=True, verbose_name='Create date')
    updated = models.DateTimeField(auto_now=True, verbose_name='Update')
    status=models.CharField(max_length=10, choices=STATUS_CHOISES,default='draft')
    image=models.ImageField(upload_to='porodact_images/',verbose_name='Image',blank=False)

    class Meta:
        ordering=('-publish',)
    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('blog:post_detail',args=[self.publish.year,
                                                self.publish.month,
                                                self.publish.day,
                                                self.slug])

def save_images(instance,filename):
    post_id=instance.post.id
    return 'gallery_images/{}/{}'.format(post_id,filename)

class PostPoint(models.Model):
    post_header = models.CharField(max_length=250, default='Header')
    post=models.ForeignKey(Post,on_delete=models.CASCADE,default=None)
    post_point_text=models.TextField(verbose_name='Post point')
    post_images = models.ImageField(upload_to=save_images, verbose_name='Image point', blank=True,)
    def __str__(self):
        return 'Post point {}'.format(self.post.title)

class Comment(models.Model):
    post = models.ForeignKey(Post,on_delete=models.CASCADE,related_name='comments')
    name = models.CharField(max_length=80)
    email = models.EmailField()
    body = models.TextField()
    created = models.DateTimeField(auto_now_add=True)
    updated = models.DateTimeField(auto_now=True)
    active = models.BooleanField(default=True)

    class Meta:
        ordering=('created',)

    def __str__(self):
        return 'Коментарь {} про {}'.format(self.name, self.post)

class Tag(models.Model):
    name = models.CharField(max_length=50)
    def __str__(self):
        return self.name

class TagModel(models.Model):
    title = models.CharField(max_length=100)
    tags = models.ManyToManyField(Tag)
    def __str__(self):
        return self.title

class Trip(models.Model):
    name = models.CharField(max_length=255)
    description = models.TextField()
    tags = models.CharField(max_length=255, blank=True)
    def __str__(self):
        return self.name

Webapp-master/mysite/blog/forms.py
from django import forms
from django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User
from .models import Comment
from .models import Trip
from django.core.validators import ValidationError

class CommentForms(forms.ModelForm):
    class Meta:
        model = Comment
        fields = ("name","email","body")


class SearchForm(forms.ModelForm):
    tags = forms.CharField(label="Tags", max_length=255, help_text="Enter one or more tags, separated by commas")

    class Meta:
        model = Trip
        fields = ("name", "tags", "description")

class RegistrationForm(UserCreationForm):
    email = forms.CharField(max_length=30,label="email", required=True, help_text="Обов'язкове поле", widget=forms.TextInput(attrs={
        'placeholder': 'Enter your email address',
        "id": "inputEmail",
        "class": "form",
    }))
    first_name = forms.CharField(max_length=30, required=True, help_text="Обов'язкове поле", widget=forms.TextInput(attrs={
        "class":"form-control",
        "placeholder":"login",
        "id":"inputFirstName",

    }))
    last_name = forms.CharField(max_length=30, required=True, help_text="Обов'язкове поле", widget=forms.TextInput(attrs={
        "id":"inputLastName",
        "class":"form-control",
        "placeholder":"login",
    }))

    class Meta:
        model = User
        fields = [
            'username','email', 'first_name',
            'last_name', 'password1', 'password2'
        ]

        def __init__(self, *args, **kwargs):
            super(RegistrationForm).__init__(*args, **kwargs)
            self.fields['username'].help_texts = "Обов'язкове поле тільки букви, цифри та символи @/./+/-/_."
            self.fields['password1'].help_texts = "Обов'язково використовувати букви та цифри"
            self.fields['password2'].help_texts = "Повторіть ще раз свій пароль"

class LoginForm(forms.Form):
    username=forms.CharField(widget=forms.TextInput(attrs={
        "id":"inputLogin",
        "class":"form-control",
        "placeholder":"login",
    }))
    password=forms.CharField(widget=forms.PasswordInput(attrs={
        "type": "password",
        "id":"inputPassword",
        "class":"form-control",
        "placeholder":"0000",
    }))

Webapp-master/mysite/blog/views.py
from django.shortcuts import get_object_or_404, render, redirect
from django.core.paginator import Paginator,EmptyPage,PageNotAnInteger
from django.views.generic import ListView
from django.contrib.auth.views import LoginView
from django.views import View
from .models import Post, PostPoint, Comment, User
from .forms import CommentForms, LoginForm, RegisterForm
from django.db.models import Count
from django.http import HttpResponse
from django.contrib.auth import authenticate, login, logout
from django.contrib.auth.forms import UserCreationForm
from django.contrib import messages
from django.contrib.auth.decorators import login_required
class PostListView(ListView):
    queryset = Post.objects.all()
    context_object_name = 'posts'
    paginate_by = 3
    template_name = 'blog/post/list.html'

from taggit.models import Tag

@login_required(login_url='blog:login')
def post_list(request, tag_slug=None):
    object_list=Post.objects.all()
    tag = None
    if tag_slug:
        tag = get_object_or_404(Tag, slug=tag_slug)
        object_list = object_list.filter(tags__in=[tag])
    items_per_page = 3
    paginator=Paginator(object_list, items_per_page)
    page = request.GET.get('page', 1)
    try:
        posts=paginator.page(page)
    except PageNotAnInteger:
        posts=paginator.page(1)
    except EmptyPage:
        posts=paginator.page(paginator.num_pages)
    return render(request,'blog/post/list.html',{'posts':posts})




def post_detail(request, year, month, day, post):
    post_object = get_object_or_404(Post, slug=post, status='published',
                                    publish__year=year,
                                    publish__month=month,
                                    publish__day=day)
    post_points = PostPoint.objects.filter(post=post_object)

    comments = post_object.comments.filter(active=True)
    new_comment = None
    if request.method == 'POST':

        comment_form = CommentForms(data=request.POST)
        if comment_form.is_valid():
            cd = comment_form.cleaned_data
            new_comment = Comment(post=post_object, name=cd['name'], email=cd['email'], body=cd['body'])
            new_comment.save()
    else:
        comment_form = CommentForms()

    post_tags_ids=post_object.tags.values_list('id',flat=True)
    similar_posts=Post.objects.filter(tags__in=post_tags_ids,status='published').exclude(id=post_object.id)
    similar_posts=similar_posts.annotate(same_tags=Count('tags')).order_by('-same_tags','-publish')[:3]

    return render(request, 'blog/post/detail.html', {'post': post_object,
                                                     'post_points': post_points,
                                                     'comments': comments,
                                                     'new_comment': new_comment,
                                                     'comment_form': comment_form,
                                                     'similar_posts': similar_posts
                                                     })

@login_required(login_url='blog:login')
def login(request):
    if request.method == 'POST':
        username = request.POST.get('username')
        password = request.POST.get('password')

        user = authenticate(request, username=username, password=password)

        if user is not None:
            login(request, user)
            return redirect('home')
        else:
            messages.info(request, 'Username or password is incorrect!')
    context = {}
    return render(request, 'registration/login.html', context)

def logout_view(request):
    messages.success(request, 'Successfully logged out')
    logout(request)
    return redirect('login')

def register(request):
    form = UserCreationForm()

    if request.method == 'POST':
        form = RegisterForm(request.POST)
        if form.is_valid():
            form.save()
            user = form.cleaned_data.get('username')
            messages.success(request, 'Account was created for ' + user)
            return redirect('login')

    context = {'form':form}
    return render(request, 'registration/register.html', context)

def home(request):
    if 'user' in request.session:
        current_user = request.session['user']
        param = {'current_user':current_user}
        return render(request, 'blog/base.html', param)
    else:
        return redirect('login')
    return render(request, 'registration/login.html')


@login_required
def profile(request):
    return render(request, 'blog/account/dashboard.html')

Webapp-master/mysite/blog/templates/blog/post/detail.html
{% extends 'blog/base.html' %}
{% block title %}
    {{ post.title }}
{% endblock %}
{% block content %}
    <div class="container my-3">
        <div class="card-deck">
            <div class="card">
                <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                <div class="card-body">
                    <h5 class="card-title">{{ post.title }}</h5>
                    <p class="card-text">{{ post.short_description }}</p>
                </div>
                {% for post_point in post_points %}
                    <div class="card-body">
                        <h5 class="card-title">{{ post_point.post_point_header}}</h5>
                        {% if post_point.post_image %}
                            <img src="{{ MEDIA_URL }}{{ post_point.post_image.url }}" class="card-img-top" alt="..."
                            style="width: 500px">
                        {% endif %}
                        {% if post_point.post_point_header == "Подорожі" %}
                            <p class="card-text">{{ post_point.post_point_text }}</p>
                        {% else %}
                            <p class="card-text">{{ post_point.post_point_text }}</p>
                        {% endif %}

                    </div>
                {% endfor %}
                <div class="card-footer">
                    <small class="text-muted">Опубліковано {{ post.publish }}. Автор {{ post.author }}</small>
                </div>
            </div>
        </div>
    </div>
{% with comments.count as total_comments %}
    <h3>Всього коментарів: {{total_comments}}</h3>
{% endwith %}

{% for comment in comments %}
    <div class="card border-dark mb-3">
        <div class="card-header">
           <h4>{{comment.name}}.</h4>   <b>E-mail: {{comment.email}}</b>
        </div>
        <div class="card-body text-dark">
            <p class="card-text"> <b>{{ forloop.counter }}.</b>  {{ comment.body }} </p>
        </div>
    </div>
{% endfor %}
    <div class="m-5">

    {% if new_comment %}
        <h2>Ваш коментарій додано</h2>
    {% else %}
        <h2>Додати коментарій</h2>
            <form action="." method="post">
            <div class="form-group">
            <label for="nameInput">Ім'я</label>
    {{ comment_form.name }}
    </div>
    <div class="form-group">
        <label for="exampleInputEmail1">Ваш Email </label>
        {{ comment_form.email }}
        {% if comment_form.errors.email %}
            <p>{{ comment_form.errors.email }}</p>
        {% endif %}
    </div>
    <div class="form-group">
        <label for="comment">Ваш коментарій</label>
        {{ comment_form.body }}
    </div>
        <button type="submit" class="btn btn-primary">Додати коментарій</button>
        {% csrf_token %}
</form>
{% endif %}
</div>
<div class="m-5" >
    <h2>  Cхожі пости </h2>
    {% for post in similar_posts %}
    <p>
        <a href="{{ post.get_absolut_url }}"> {{ post.title }} </a>
    </p>
    {% empty %}
        here are no similar posts yet
    {% endfor %}
</div>

{% endblock %}

Webapp-master/mysite/blog/templates/blog/post/list.html
{%extends 'blog/base.html'%}
{%block title%} My blog {% endblock %}
{%block content%}
    <h1 class="title text-center my-3">Подорожі по Україні</h1>
    <div class="container">
        {% if tag %}
            <h2 class="text-center">Tags: {{tag.name}}</h2>
         {% endif %}

        <div class="card-deck">
            {% for post in posts %}
                <div class="card">
                    <a href="{{ post.get_absolute_url }}">
                        <img src="{{ MEDIA_URL }}{{ post.image.url }}" class="card-img-top" alt="...">
                    </a>
                    <div class="card-body">
                        <a href="{{ post.get_absolute_url }}">
                            <h5 class="card-title">{{ post.title }}</h5>
                        </a>
                        <p class="card-text">{{ post.short_description }}</p>
                    </div>
                    <div class="card-footer">
                        <small class="text-muted">Опубліковано {{ post.publish }}. Автор {{ post.author }}</small>
                        <p>
                          {% for tag in post.tags.all %}
                            <a href="{% url 'blog:post_list_by_tag' tag.slug %}">
                                {{tag.name}}
                            </a>
                           {% if not forloop.last %}, {% endif %}
                           {% endfor %}
                        </p>
                    </div>
                </div>
            {% endfor %}
        </div>
    </div>

{% include 'paginations.html' with page=posts %}
{% endblock %}

Webapp-master/mysite/blog/templates/blog/post/search.html
{% extends "blog/base.html" %}
{% block content %}
    <h1>Search trips by tags</h1>
    <form method="get">
        {{ form.as_p }}
        <input type="submit" value="Search">
    </form>
    {% if trips %}
        <h2>Search results</h2>
        <ul>
            {% for trip in trips %}
                <li>
                    {{ trip.name }} - {{ trip.description }} - {{ trip.tags }}
                </li>
            {% endfor %}
        </ul>
    {% endif %}
{% endblock %}